### ISSUE TITLE
Shows "INCOMPLETE due to violating max accel" on first run

### ISSUE THREAD

**Issue by gulshan216** [PhilippeW83440/CarND-Path-Planning-Project#2]
Hi, I get the following message within the first couple of seconds of starting with the simulator for the first time:
"INCOMPLETE due to violating max accel"

Steps taken:
1) $git clone https://github.com/PhilippeW83440/CarND-Path-Planning-Project.git
2) $bash ./install-ubuntu.sh(I had to uncomment out the command "git checkout e94b6e1" as I was getting an error while building without it)
3) $mkdir build && cd build
4) cmake .. && make
5) ./path_planning
6) Started the simulator

Do you know what is going wrong here

**Comment by gulshan216** [comment]
It works fine if I use the Udacity Term 3 simulator and Term 3 highway map.

**Comment by kecaiwu** [comment]
uncomment the 'check_max_capabilities()' function in cost.cpp. @gulshan216

**Comment by gulshan216** [comment]
Thanks a lot for the tip.
Just 1 problem with that though check_max_capabilities() is expecting trajectory of type vector<vector<double>> , but in the constructor Cost we are passing the trajectory of type TrajectoryXY.
After doing the type conversion, this works perfectly on the Bosch challenge track.

**Comment by gulshan216** [comment]
@kecaiwu Just reopened in case you have the rights to fix this issue. If not I can just close this.
