### ISSUE TITLE
The URL for JMT is broken.

### ISSUE THREAD

**Issue by kimna4** [PhilippeW83440/CarND-Path-Planning-Project#3]
Hello, 
Thank you for sharing your project.

The url for JMT ( http://www.shadmehrlab.org/book/minimum_jerk/minimumjerk.htm ) is not available.

Could you check this url?

Thank you

**Comment by PhilippeW83440** [comment]
It is there now http://courses.shadmehrlab.org/Shortcourse/minimumjerk.pdf

**Comment by PhilippeW83440** [comment]
It is fixed now. README updated.
