### ISSUE TITLE
Bosch_Challenge: Error of violating max. acceleration

### ISSUE THREAD

**Issue by cheenng** [PhilippeW83440/CarND-Path-Planning-Project#4]
Hi @PhilippeW83440  ,

thank you for sharing your project. 
I checked out your master branch and compiled it. I didn't modify your code. As I started the simulator "bosch_final_linux/bosch_challenge.x86_64  and run ./path_planning , an error on simulator jumped out immediately due to violating max accel. Please see the screenshot below.

Any idea how should I fix this quickly?

Thank you so much.

Regards,
Yuan

![image](https://user-images.githubusercontent.com/33980814/86339801-4f2f5c00-bc54-11ea-8c3b-f488cf284858.png)

**Comment by PhilippeW83440** [comment]
In trajectory.cpp, at low speed, starting the race, use:
sf      = si + 1 * sf_dot * T;
instead of
sf      = si + 2 * sf_dot * T; // line 204
To have a less aggressive start. It may help. With the simulator, from machine to machine, there are some different latencies

Let me know if it helps.

**Comment by cheenng** [comment]
Your solution works. Thank you.
